# Generated by Django 2.1.15 on 2020-07-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='iplanner_rate',
            field=models.FloatField(blank=True, db_column='iPlannerRate', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user_rate',
            field=models.FloatField(blank=True, db_column='UserRate', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(blank=True, db_column='Active', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, db_column='CityId', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deal_discount',
            field=models.FloatField(blank=True, db_column='DealDiscount', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, db_column='Lat', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.FloatField(blank=True, db_column='Long', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='my_property',
            field=models.IntegerField(blank=True, db_column='MyProperty', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.FloatField(blank=True, db_column='Rate', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sold_deal_quantity',
            field=models.IntegerField(blank=True, db_column='SoldDealQuantity', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='SubCategoryId', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.SubCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_deal_quantity',
            field=models.IntegerField(blank=True, db_column='TotalDealQuantity', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='usage_deadline',
            field=models.IntegerField(blank=True, db_column='UsageDeadline', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit_date_from',
            field=models.DateTimeField(blank=True, db_column='VisitDateFrom', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit_date_to',
            field=models.DateTimeField(blank=True, db_column='VisitDateTo', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit_duration',
            field=models.IntegerField(blank=True, db_column='VisitDuration', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit_time_from',
            field=models.IntegerField(blank=True, db_column='VisitTimeFrom', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit_time_to',
            field=models.IntegerField(blank=True, db_column='VisitTimeTo', null=True),
        ),
    ]
