# Generated by Django 2.1.15 on 2020-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200714_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='base_url',
            field=models.CharField(blank=True, db_column='BaseUrl', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='full_title',
            field=models.CharField(blank=True, db_column='FullTitle', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url_key',
            field=models.CharField(blank=True, db_column='UrlKey', max_length=200, null=True),
        ),
    ]
