# Generated by Django 2.1.15 on 2020-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200714_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.IntegerField(db_column='AttractionType', default=0, verbose_name='Attraction Type'),
        ),
    ]
