# Generated by Django 2.1.15 on 2020-07-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_attraction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecl_dist', models.FloatField(blank=True, null=True, verbose_name='Euclidean Distance')),
                ('len_meter', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Meters')),
                ('len_time', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Time')),
                ('route', models.TextField(blank=True, null=True, verbose_name='Routing Json')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='catalog.Attraction')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_mat', to='catalog.Attraction')),
            ],
            options={
                'verbose_name_plural': '6 Distance matrix',
                'db_table': 'plan_distance_mat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='Day Of Tour')),
                ('all_days', models.IntegerField(blank=True, null=True, verbose_name='Total days')),
                ('coh_fullTime', models.FloatField(blank=True, null=True, verbose_name='Coefficient of Fill full time Cost')),
                ('coh_lengthTime', models.FloatField(blank=True, null=True, verbose_name='Coefficient of distance length time Cost')),
                ('coh_countPoints', models.FloatField(blank=True, null=True, verbose_name='Coefficient of count of points Cost')),
                ('coh_minRqTime', models.FloatField(blank=True, null=True, verbose_name='Coefficient of diff min required Time Cost')),
                ('cost_fullTime', models.FloatField(blank=True, null=True, verbose_name='Fill full time Cost')),
                ('cost_lengthTime', models.FloatField(blank=True, null=True, verbose_name='Distance length time Cost')),
                ('cost_countPoints', models.FloatField(blank=True, null=True, verbose_name='Count of points Cost')),
                ('cost_minRqTime', models.FloatField(blank=True, null=True, verbose_name='Diff min required Time Cost')),
                ('cost_rate', models.FloatField(blank=True, null=True, verbose_name='Selection attraction rate Cost')),
                ('rank', models.FloatField(blank=True, null=True, verbose_name='Average Rank')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Start Time of Day')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='End Time of Day')),
                ('dist_len', models.FloatField(blank=True, null=True, verbose_name='Length of distance times')),
                ('points_len', models.IntegerField(blank=True, null=True, verbose_name='Count of points used')),
                ('duration_len', models.FloatField(blank=True, null=True, verbose_name='Length of duration points')),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
            ],
            options={
                'verbose_name_plural': '7 Plan',
                'db_table': 'plan_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('len_time', models.IntegerField()),
                ('from_time', models.IntegerField(blank=True, null=True)),
                ('dist_to', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attraction')),
            ],
            options={
                'verbose_name_plural': '7.1 Plan details',
                'db_table': 'plan_plan_details',
                'ordering': ('plan__day', 'order'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': '5 Travel Types',
                'db_table': 'plan_traveltype',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='travel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TravelType'),
        ),
    ]
